apiVersion: v1
kind: ConfigMap
metadata:
  name: wrktalk-agent-config
  namespace: default
data:
  CLIENT_ID: "101"
  GCC_API_URL: "http://mock-gcc-service.default.svc.cluster.local:5000/api/v1"
  ARGOCD_SERVER: "argocd-server.argocd.svc.cluster.local"
  ARGOCD_APP_NAME: "wrktalk-test-app"
  POLL_INTERVAL: "10"

---
apiVersion: v1
kind: Secret
metadata:
  name: wrktalk-agent-secret
  namespace: default
type: Opaque
stringData:
  ARGOCD_USERNAME: "admin"
  ARGOCD_PASSWORD: "bLYgjSASIbYvT4PG"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wrktalk-agent
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wrktalk-agent
  template:
    metadata:
      labels:
        app: wrktalk-agent
    spec:
      containers:
      - name: agent
        image: wrktalk-agent:latest
        imagePullPolicy: IfNotPresent
        env:
        # From ConfigMap
        - name: CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: wrktalk-agent-config
              key: CLIENT_ID
        - name: GCC_API_URL
          valueFrom:
            configMapKeyRef:
              name: wrktalk-agent-config
              key: GCC_API_URL
        - name: ARGOCD_SERVER
          valueFrom:
            configMapKeyRef:
              name: wrktalk-agent-config
              key: ARGOCD_SERVER
        - name: ARGOCD_APP_NAME
          valueFrom:
            configMapKeyRef:
              name: wrktalk-agent-config
              key: ARGOCD_APP_NAME
        - name: POLL_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: wrktalk-agent-config
              key: POLL_INTERVAL
        # From Secret
        - name: ARGOCD_USERNAME
          valueFrom:
            secretKeyRef:
              name: wrktalk-agent-secret
              key: ARGOCD_USERNAME
        - name: ARGOCD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wrktalk-agent-secret
              key: ARGOCD_PASSWORD
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi