apiVersion: v1
kind: Secret
metadata:
  name: wrktalk-agent-secret
  namespace: default
type: Opaque
stringData:
  ARGOCD_AUTH_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJhZG1pbjphcGlLZXkiLCJuYmYiOjE3NjM3MDAyODMsImlhdCI6MTc2MzcwMDI4MywianRpIjoiZTRmMDg1MjQtZmIwMS00NDg3LTgwNmUtZDhmNzVkNDZlMjQ4In0.RUgCctokZxZ-rItPWEJ_uookFwzMZ2GihLqNxmBAHHQ"
